
import React, { useState, useCallback } from 'react';
import { StyleAnalysis, Gender } from './types';
import { analyzeStyle } from './services/geminiService';
import Landing from './components/Landing';
import Analyzer from './components/Analyzer';
import Results from './components/Results';
import LoadingOverlay from './components/LoadingOverlay';

const App: React.FC = () => {
  const [view, setView] = useState<'landing' | 'analyzer' | 'results'>('landing');
  const [loading, setLoading] = useState(false);
  const [analysis, setAnalysis] = useState<StyleAnalysis | null>(null);
  const [error, setError] = useState<string | null>(null);

  const handleStart = () => {
    setView('analyzer');
  };

  const handleAnalyze = async (image: string, gender: Gender) => {
    setLoading(true);
    setError(null);
    try {
      // Remove base64 prefix if exists
      const base64Data = image.split(',')[1] || image;
      const result = await analyzeStyle(base64Data, gender);
      setAnalysis(result);
      setView('results');
    } catch (err: any) {
      console.error(err);
      setError(err.message || "Something went wrong during analysis.");
    } finally {
      setLoading(false);
    }
  };

  const handleReset = () => {
    setAnalysis(null);
    setView('landing');
  };

  return (
    <div className="min-h-screen flex flex-col">
      {/* Header */}
      <header className="sticky top-0 z-50 glass shadow-sm bg-white/80">
        <div className="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8 h-16 flex items-center justify-between">
          <div className="flex items-center space-x-2 cursor-pointer" onClick={handleReset}>
            <div className="bg-pink-500 text-white p-1.5 rounded-lg">
              <svg xmlns="http://www.w3.org/2000/svg" className="h-6 w-6" fill="none" viewBox="0 0 24 24" stroke="currentColor">
                <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M12 4v1m6 11h2m-6 0h-2v4m0-11v3m0 0h.01M12 12h4.01M16 20h4M4 12h4m12 0h.01M5 8h2a1 1 0 001-1V5a1 1 0 00-1-1H5a1 1 0 00-1 1v2a1 1 0 001 1zm12 0h2a1 1 0 001-1V5a1 1 0 00-1-1h-2a1 1 0 00-1 1v2a1 1 0 001 1zM5 20h2a1 1 0 001-1v-2a1 1 0 00-1-1H5a1 1 0 00-1 1v2a1 1 0 001 1z" />
              </svg>
            </div>
            <span className="text-xl font-bold bg-clip-text text-transparent bg-gradient-to-r from-pink-600 to-rose-600">StyleAI</span>
          </div>
          <nav className="hidden md:flex space-x-8 text-sm font-medium text-gray-600">
            <button onClick={handleReset} className="hover:text-pink-600 transition-colors">Home</button>
            <button className="hover:text-pink-600 transition-colors">Features</button>
            <button className="hover:text-pink-600 transition-colors">About</button>
            <button onClick={handleStart} className="text-pink-600 font-semibold border-b-2 border-pink-500">Try It</button>
          </nav>
        </div>
      </header>

      <main className="flex-grow">
        {view === 'landing' && <Landing onStart={handleStart} />}
        {view === 'analyzer' && <Analyzer onAnalyze={handleAnalyze} error={error} />}
        {view === 'results' && analysis && <Results analysis={analysis} onReset={() => setView('analyzer')} />}
      </main>

      <footer className="bg-gray-900 text-gray-400 py-8">
        <div className="max-w-7xl mx-auto px-4 text-center">
          <p className="mb-2">© 2026 StyleAI. Powered by Advanced Gemini AI Technology.</p>
          <p className="text-xs">All styling recommendations are generated by AI for inspiration.</p>
        </div>
      </footer>

      {loading && <LoadingOverlay />}
    </div>
  );
};

export default App;
